name: "CI/CD Pipeline for LMS Front-End"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the repo
      uses: actions/checkout@v3

    - name: Installing NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installing SASS
      run: npm install -g sass

    - name: Compiling SCSS files to CSS
      run: sass scss:css

    - name: Zipping to deploy
      run: zip -r dist.zip css js pages index.html

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Deploying the zip
      uses: gcloud compute scp dist.zip dep-9-vm:/opt/apache/apache-tomcat-10.1.1/webapps/lms-backend

    - name: Clean up old stuff
      run: >
        gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
        --commands="sudo rm -rf /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/css
        /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/pages
        /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/js
        /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/index.html
        "

    - name: Extracting zip
      run: >
        gcloud compute ssh --zone="asia-south1-a" dep-9-vm
        --commands="sudo unzip /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/dist.zip"

    - name: Cleaning left overs
      run: >
        gcloud compute ssh --zone="asia-south1-a" dep-9-vm
        --commands="sudo rm /opt/apache/apache-tomcat-10.1.1/webapps/lms-backend/dist.zip"


      


