name: "CI/CD Pipeline for LMS Front-End"
on: 
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the latest commit 
        uses: actions/checkout@v3

      - name: Installing node js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing Sass
        run: npm install -g sass

      - name: Compiling Scss files to css
        run: sass scss:css

      - name: Creates the dist directory
        run: mkdir dist

      - name: Copying everything to the dist directory
        run: cp -r css pages js index.html dist/

      - name: Creating a zip file for deployment
        run: zip -r dist.zip dist/

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'

        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy the dist.zip
        uses: gcloud compute scp --zone="asia-south1-a" dist.zip root@dep-9-vm:/opt